numbers = {
    1: "Bir",
    2: "Ikki",
    3: "Uch",
    4: "To'rt",
    5: "Besh",
    6: "Olti",
    7: "Yetti",
    8: "Sakkiz",
    9: "To'qqiz",
    10: "O'n",
    11: "O'n bir",
    12: "O'n ikki",
    13: "O'n uch",
    14: "O'n to'rt",
    15: "O'n besh",
    16: "O'n olti",
    17: "O'n yetti",
    18: "O'n sakkiz",
    19: "O'n to'qqiz",
    20: "Yigirma",
    21: "Yigirma bir",
    22: "Yigirma ikki",
    23: "Yigirma uch",
    24: "Yigirma to'rt",
    25: "Yigirma besh",
    26: "Yigirma olti",
    27: "Yigirma yetti",
    28: "Yigirma sakkiz",
    29: "Yigirma to'qqiz",
    30: "O'ttiz",
    31: "O'ttiz bir",
    32: "O'ttiz ikki",
    33: "O'ttiz uch",
    34: "O'ttiz to'rt",
    35: "O'ttiz besh",
    36: "O'ttiz olti",
    37: "O'ttiz yetti",
    38: "O'ttiz sakkiz",
    39: "O'ttiz to'qqiz",
    40: "Qirq",
    41: "Qirq bir",
    42: "Qirq ikki",
    43: "Qirq uch",
    44: "Qirq to'rt",
    45: "Qirq besh",
    46: "Qirq olti",
    47: "Qirq yetti",
    48: "Qirq sakkiz",
    49: "Qirq to'qqiz",
    50: "Ellik",
    51: "Ellik bir",
    52: "Ellik ikki",
    53: "Ellik uch",
    54: "Ellik to'rt",
    55: "Ellik besh",
    56: "Ellik olti",
    57: "Ellik yetti",
    58: "Ellik sakkiz",
    59: "Ellik to'qqiz",
    60: "Oltmish",
    61: "Oltmish bir",
    62: "Oltmish ikki",
    63: "Oltmish uch",
    64: "Oltmish to'rt",
    65: "Oltmish besh",
    66: "Oltmish olti",
    67: "Oltmish yetti",
    68: "Oltmish sakkiz",
    69: "Oltmish to'qqiz",
    70: "Yetmish",
    71: "Yetmish bir",
    72: "Yetmish ikki",
    73: "Yetmish uch",
    74: "Yetmish to'rt",
    75: "Yetmish besh",
    76: "Yetmish olti",
    77: "Yetmish yetti",
    78: "Yetmish sakkiz",
    79: "Yetmish to'qqiz",
    80: "Sakson",
    81: "Sakson bir",
    82: "Sakson ikki",
    83: "Sakson uch",
    84: "Sakson to'rt",
    85: "Sakson besh",
    86: "Sakson olti",
    87: "Sakson yetti",
    88: "Sakson sakkiz",
    89: "Sakson to'qqiz",
    90: "To'qson",
    91: "To'qson bir",
    92: "To'qson ikki",
    93: "To'qson uch",
    94: "To'qson to'rt",
    95: "To'qson besh",
    96: "To'qson olti",
    97: "To'qson yetti",
    98: "To'qson sakkiz",
    99: "To'qson to'qqiz",
    100: "Yuz"
}
